// Hand-authored so it can produce the `SvgIconNameTypes` literal union that gives
// Icon `name` its intellisense - Vite's import.meta.glob only yields `string`
// keys, so the union can't be derived from the filesystem at type-check time.
// Kept in sync with src/assets/svgs by the drift check in icon-names.spec.ts.
export const svgIconNames = [
  "add",
  "anchor",
  "archive",
  "arrow_back",
  "arrow_downward",
  "arrow_forward",
  "arrow_upward",
  "attach_file",
  "bookmark",
  "bookmark-fill",
  "calendar_month",
  "call",
  "cancel",
  "chat",
  "check",
  "check_circle",
  "chevron_left",
  "chevron_right",
  "close",
  "code",
  "content_copy",
  "dark_mode",
  "delete",
  "description",
  "download",
  "edit",
  "error",
  "favorite",
  "favorite-fill",
  "filter_list",
  "flight",
  "folder",
  "github",
  "group",
  "help",
  "home",
  "home-fill",
  "image",
  "inbox",
  "info",
  "keyboard_arrow_down",
  "keyboard_arrow_up",
  "language",
  "light_mode",
  "link",
  "location_on",
  "lock",
  "lock_open",
  "luggage",
  "mail",
  "menu",
  "more_horiz",
  "more_vert",
  "notifications",
  "notifications-fill",
  "open_in_new",
  "person",
  "refresh",
  "remove",
  "schedule",
  "search",
  "send",
  "settings",
  "share",
  "shopping_cart",
  "star",
  "star-fill",
  "upload",
  "visibility",
  "visibility_off",
  "warning",
] as const;

export type SvgIconNameTypes = (typeof svgIconNames)[number];
